### ISSUE TITLE
Harmony: Autocomplete

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/bricks#669]
<img width="224" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/d2cad27b-a306-4696-985d-25833a817d61">
<img width="444" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/7c4e747b-7bd3-41bf-b34f-36c328bbdc0d">

**Comment by 9teen90nine** [comment]
1. Create css module 
2. Create a story for a case with a button on top
