### ISSUE TITLE
Harmony: EstimateDropdown

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/bricks#672]
<img width="224" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/9e6d9a8c-1cdd-4faf-ae5c-4a28bd880728">
<img width="235" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/dca6abe6-78ee-48b7-8f89-56fe0d5c82cd">
<img width="228" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/72720fa2-533d-4f88-a6a5-a9379661a0c9">
<img width="225" alt="image" src="https://github.com/taskany-inc/bricks/assets/982072/55e5300b-b66a-4d8e-83d4-033e3f975d52">

**Comment by 9teen90nine** [comment]
Should be decomposible so data-attributes for e2e could be used
