### ISSUE TITLE
Harmony: select updates

### ISSUE THREAD

**Issue by 9teen90nine** [taskany-inc/bricks#769]
Added new versions + updated arrow which stays across the content:

1. Fix arrow position
2. Add filled view
3. Add classes for each view (error, filled)

https://www.figma.com/file/3xsUrRBsEJTBrJ27gMhSGZ/Taskany-(Goals)-New?type=design&node-id=2923-55748&mode=design&t=bSkmaS6LpUO5NGd8-4

**Comment by LamaEats** [comment]
Closed with #895 (https://github.com/taskany-inc/bricks/pull/895)
